/* 
DROP TABLE OrdenDetalles
DROP TABLE Ordenes
*/

CREATE DATABASE SuizaLabDB
GO
USE SuizaLabDB
GO

CREATE TABLE Ordenes
(
  ID INT PRIMARY KEY IDENTITY(1,1),
  FECHACREACION DATETIME NOT NULL,
  CLIENTE VARCHAR(100) NOT NULL,
  TOTAL DECIMAL(18,2) NOT NULL
)
GO

CREATE TABLE OrdenDetalles
(
  ID INT PRIMARY KEY IDENTITY(1,1),
  ORDENID INT NOT NULL,
  PRODUCTO VARCHAR(100) NOT NULL,
  CANTIDAD INT NOT NULL,
  PRECIOUNITARIO DECIMAL(18,2) NOT NULL,
  SUBTOTAL DECIMAL(18,2) NOT NULL
)
GO

ALTER TABLE OrdenDetalles ADD CONSTRAINT FK_ORDENES FOREIGN KEY (ORDENID) references ORDENES(ID)

/*
INSERT INTO Ordenes VALUES(GETDATE(), 'Tottus', 25.3)
DECLARE @ORID INT
SELECT @ORID = SCOPE_IDENTITY();
INSERT INTO OrdenDetalles VALUES(@ORID, 'Leche', 1, 2.5, 2.5)
INSERT INTO OrdenDetalles VALUES(@ORID, 'Azúcar', 3, 5.6, 16.8)
INSERT INTO OrdenDetalles VALUES(@ORID, 'Arroz', 2, 3, 6)

DBCC CHECKIDENT ('Ordenes', RESEED, 0);

SELECT * FROM ORDENDETALLES
SELECT * FROM ORDENES

SELECT * FROM ORDENES O
JOIN ORDENDETALLES OD ON OD.ORDENID = O.ID

EXECUTE SP_ELIMINAR_ORDEN_POR_ID @ID = 1
EXECUTE SP_OBTENER_ORDEN_POR_ID @ID = 1
*/