/* 
DROP TABLE OrdenDetalles
DROP TABLE Ordenes
*/

CREATE DATABASE SuizaLabDB
GO
USE SuizaLabDB
GO

CREATE TABLE Ordenes
(
  ID INT PRIMARY KEY IDENTITY(1,1),
  FECHACREACION DATETIME NOT NULL,
  CLIENTE VARCHAR(100) NOT NULL,
  TOTAL DECIMAL(18,2) NOT NULL
)
GO

CREATE TABLE OrdenDetalles
(
  ID INT PRIMARY KEY IDENTITY(1,1),
  ORDENID INT NOT NULL,
  PRODUCTO VARCHAR(100) NOT NULL,
  CANTIDAD INT NOT NULL,
  PRECIOUNITARIO DECIMAL(18,2) NOT NULL,
  SUBTOTAL DECIMAL(18,2) NOT NULL
)
GO

ALTER TABLE OrdenDetalles ADD CONSTRAINT FK_ORDENES FOREIGN KEY (ORDENID) references ORDENES(ID)

/*
INSERT INTO Ordenes VALUES(GETDATE(), 'Tottus', 25.3)
DECLARE @ORID INT
SELECT @ORID = SCOPE_IDENTITY();
INSERT INTO OrdenDetalles VALUES(@ORID, 'Leche', 1, 2.5, 2.5)
INSERT INTO OrdenDetalles VALUES(@ORID, 'Azúcar', 3, 5.6, 16.8)
INSERT INTO OrdenDetalles VALUES(@ORID, 'Arroz', 2, 3, 6)

DBCC CHECKIDENT ('Ordenes', RESEED, 0);

SELECT * FROM ORDENDETALLES
SELECT * FROM ORDENES

SELECT * FROM ORDENDETALLES WHERE ORDENID = 2
SELECT * FROM ORDENES WHERE ID = 2
declare @FINI DATE = '2025-07-05'
SELECT *, CONVERT(VARCHAR(10), FECHACREACION, 103),CONVERT(VARCHAR(10), @FINI,112), DATEPART(FECHACREACION)  FROM ORDENES O
JOIN ORDENDETALLES OD ON OD.ORDENID = O.ID

EXECUTE SP_ELIMINAR_ORDEN_POR_ID @ID = 1
EXECUTE SP_OBTENER_ORDEN_POR_ID @ID = 1

declare @CLIE VARCHAR(100) = 'SA'
declare @FINI DATE = NULL
declare @FFIN DATE = '2025-07-03'

IF @FINI IS NOT NULL AND @FFIN IS NULL
begin
print ('first')
SELECT * FROM ORDENES
WHERE FORMAT(FECHACREACION,'yyyy-MM-dd') >= FORMAT(@FINI,'yyyy-MM-dd') AND (@CLIE IS NULL OR CLIENTE LIKE '%' + @CLIE + '%')
end
ELSE IF @FINI IS NULL AND @FFIN IS NOT NULL
begin
print ('second')
SELECT * FROM ORDENES
WHERE FORMAT(FECHACREACION,'yyyy-MM-dd') <= FORMAT(@FFIN,'yyyy-MM-dd') AND (@CLIE IS NULL OR CLIENTE LIKE '%' + @CLIE + '%')
end
ELSE IF @FINI IS NOT NULL AND @FFIN IS NOT NULL
begin
print ('third')
SELECT * FROM ORDENES
WHERE FORMAT(FECHACREACION,'yyyy-MM-dd') BETWEEN FORMAT(@FINI,'yyyy-MM-dd') AND FORMAT(@FFIN,'yyyy-MM-dd') AND (@CLIE IS NULL OR CLIENTE LIKE '%' + @CLIE + '%')
end
ELSE
begin
print ('fourth')
SELECT * FROM ORDENES
WHERE (@CLIE IS NULL OR CLIENTE LIKE '%' + @CLIE + '%')
end

WHERE CONVERT(VARCHAR(10),FECHACREACION,112) >= CONVERT(VARCHAR(10),@FINI,112) AND CONVERT(VARCHAR(10),FECHACREACION,112) <= CONVERT(VARCHAR(10),@FFIN,112)

SELECT * FROM ORDENES
WHERE (@CLIEN IS NULL OR CLIENTE LIKE '%' + @CLIEN + '%') AND (@FINI IS NULL OR  >= CONVERT(VARCHAR(10),@FINI,103) AND CONVERT(VARCHAR(10),FECHACREACION,103) <= CONVERT(VARCHAR(10),@FFIN,103))


EXEC SP_LISTAR_ORDENES @CLIE = 'sa', @FFIN = '2025-07-03'
*/