CREATE DATABASE SuizaLabDB
GO
USE SuizaLabDB
GO

CREATE TABLE Ordenes
(
  ID INT PRIMARY KEY IDENTITY(1,1),
  FECHACREACION DATETIME,
  CLIENTE VARCHAR(100),
  TOTAL DECIMAL
)
GO

CREATE TABLE OrdenesDetalles
(
  ID INT PRIMARY KEY IDENTITY(1,1),
  ORDENID INT,
  PRODUCTO VARCHAR(100),
  CANTIDAD INT,
  PRECIOUNITARIO DECIMAL,
  SUBTOTAL DECIMAL
)
GO

ALTER TABLE OrdenesDetalles ADD CONSTRAINT FK_ORDENES FOREIGN KEY (ORDENID) references ORDENES(ID)