ALTER PROCEDURE SP_OBTENER_ORDEN_POR_ID
	@ID INT
AS
BEGIN
	SELECT * FROM ORDENES
	WHERE ID = @ID

	SELECT * FROM ORDENDETALLES
	WHERE ORDENID = @ID
END
GO

ALTER PROCEDURE SP_ELIMINAR_ORDEN_POR_ID
	@ID INT
AS
BEGIN
	DELETE ORDENDETALLES
	WHERE ORDENID = @ID

	DELETE ORDENES
	WHERE ID = @ID
END
GO

ALTER PROCEDURE SP_CREAR_ORDEN
	@CLIE VARCHAR(100),
	@TOTA DECIMAL(18,2),
	@ORID INT = NULL OUTPUT
AS
BEGIN
	INSERT INTO Ordenes VALUES(GETDATE(),@CLIE,@TOTA)

	SELECT @ORID = SCOPE_IDENTITY();
END

CREATE PROCEDURE SP_CREAR_ORDEN_DETALLE
	@ORID INT,
	@PROD VARCHAR(100),
	@CANT INT,
	@PUNI DECIMAL(18,2),
	@SUBT DECIMAL(18,2)
AS
BEGIN
	INSERT INTO OrdenDetalles VALUES(@ORID,@PROD,@CANT,@PUNI,@SUBT)
END