CREATE PROCEDURE SP_OBTENER_ORDEN_POR_ID
	@ID INT
AS
BEGIN
	SELECT * FROM ORDENES
	WHERE ID = @ID

	SELECT * FROM ORDENDETALLES
	WHERE ORDENID = @ID
END
GO

CREATE PROCEDURE SP_ELIMINAR_ORDEN_POR_ID
	@ID INT
AS
BEGIN
	DELETE ORDENDETALLES
	WHERE ORDENID = @ID

	DELETE ORDENES
	WHERE ID = @ID
END
GO

CREATE PROCEDURE SP_CREAR_ORDEN
	@CLIE VARCHAR(100),
	@TOTA DECIMAL(18,2),
	@ORID INT = NULL OUTPUT
AS
BEGIN
	INSERT INTO Ordenes VALUES(GETDATE(),@CLIE,@TOTA)

	SELECT @ORID = SCOPE_IDENTITY();
END

CREATE PROCEDURE SP_CREAR_ORDEN_DETALLE
	@ORID INT,
	@PROD VARCHAR(100),
	@CANT INT,
	@PUNI DECIMAL(18,2),
	@SUBT DECIMAL(18,2)
AS
BEGIN
	INSERT INTO OrdenDetalles VALUES(@ORID,@PROD,@CANT,@PUNI,@SUBT)
END

CREATE PROCEDURE SP_ACTUALIZAR_ORDEN
	@ORID INT,
	@CLIE VARCHAR(100),
	@TOTA DECIMAL(18,2)
AS
BEGIN
	UPDATE Ordenes 
	SET CLIENTE = @CLIE, TOTAL = @TOTA 
	WHERE ID = @ORID
END

CREATE PROCEDURE SP_ACTUALIZAR_ORDEN_DETALLE
	@DEID INT,
	@PROD VARCHAR(100),
	@CANT INT,
	@PUNI DECIMAL(18,2),
	@SUBT DECIMAL(18,2)
AS
BEGIN
	UPDATE OrdenDetalles
	SET PRODUCTO = @PROD, CANTIDAD = @CANT, PRECIOUNITARIO = @PUNI, SUBTOTAL = @SUBT
	WHERE ID = @DEID
END

ALTER PROCEDURE SP_LISTAR_ORDENES
	@CLIE VARCHAR(100) = '',
	@FINI DATE = NULL,
	@FFIN DATE = NULL
AS
BEGIN
	SELECT * FROM ORDENES
	WHERE (@CLIE IS NULL OR CLIENTE LIKE '%' + @CLIE + '%') --AND (CONVERT(VARCHAR(10),FECHACREACION,103) >= CONVERT(VARCHAR(10),@FINI,103) AND CONVERT(VARCHAR(10),FECHACREACION,103) <= CONVERT(VARCHAR(10),@FFIN,103))
END
GO