CREATE PROCEDURE SP_OBTENER_ORDEN_POR_ID
	@ID INT
AS
BEGIN
	SELECT * FROM ORDENES
	WHERE ID = @ID

	SELECT * FROM ORDENDETALLES
	WHERE ORDENID = @ID
END
GO

CREATE PROCEDURE SP_ELIMINAR_ORDEN_POR_ID
	@ID INT
AS
BEGIN
	DELETE ORDENDETALLES
	WHERE ORDENID = @ID

	DELETE ORDENES
	WHERE ID = @ID
END
GO

CREATE PROCEDURE SP_CREAR_ORDEN
	@CLIE VARCHAR(100),
	@TOTA DECIMAL(18,2),
	@ORID INT = NULL OUTPUT
AS
BEGIN
	INSERT INTO Ordenes VALUES(GETDATE(),@CLIE,@TOTA)

	SELECT @ORID = SCOPE_IDENTITY();
END

CREATE PROCEDURE SP_CREAR_ORDEN_DETALLE
	@ORID INT,
	@PROD VARCHAR(100),
	@CANT INT,
	@PUNI DECIMAL(18,2),
	@SUBT DECIMAL(18,2)
AS
BEGIN
	INSERT INTO OrdenDetalles VALUES(@ORID,@PROD,@CANT,@PUNI,@SUBT)
END

CREATE PROCEDURE SP_ACTUALIZAR_ORDEN
	@ORID INT,
	@CLIE VARCHAR(100),
	@TOTA DECIMAL(18,2)
AS
BEGIN
	UPDATE Ordenes 
	SET CLIENTE = @CLIE, TOTAL = @TOTA 
	WHERE ID = @ORID
END

CREATE PROCEDURE SP_ACTUALIZAR_ORDEN_DETALLE
	@DEID INT,
	@PROD VARCHAR(100),
	@CANT INT,
	@PUNI DECIMAL(18,2),
	@SUBT DECIMAL(18,2)
AS
BEGIN
	UPDATE OrdenDetalles
	SET PRODUCTO = @PROD, CANTIDAD = @CANT, PRECIOUNITARIO = @PUNI, SUBTOTAL = @SUBT
	WHERE ID = @DEID
END

ALTER PROCEDURE SP_LISTAR_ORDENES
	@CLIE VARCHAR(100) = NULL,
	@FINI DATE = NULL,
	@FFIN DATE = NULL
AS
BEGIN
	IF @FINI IS NOT NULL AND @FFIN IS NULL
	BEGIN
		SELECT * FROM ORDENES
		WHERE FORMAT(FECHACREACION,'yyyy-MM-dd') >= FORMAT(@FINI,'yyyy-MM-dd') AND (@CLIE IS NULL OR CLIENTE LIKE '%' + @CLIE + '%')
	END
	ELSE IF @FINI IS NULL AND @FFIN IS NOT NULL
	BEGIN
		SELECT * FROM ORDENES
		WHERE FORMAT(FECHACREACION,'yyyy-MM-dd') <= FORMAT(@FFIN,'yyyy-MM-dd') AND (@CLIE IS NULL OR CLIENTE LIKE '%' + @CLIE + '%')
	END
	ELSE IF @FINI IS NOT NULL AND @FFIN IS NOT NULL
	BEGIN
		SELECT * FROM ORDENES
		WHERE FORMAT(FECHACREACION,'yyyy-MM-dd') BETWEEN FORMAT(@FINI,'yyyy-MM-dd') AND FORMAT(@FFIN,'yyyy-MM-dd') AND (@CLIE IS NULL OR CLIENTE LIKE '%' + @CLIE + '%')
	END
	ELSE
	BEGIN
		SELECT * FROM ORDENES
		WHERE (@CLIE IS NULL OR CLIENTE LIKE '%' + @CLIE + '%')
	END
END
GO